# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['pid_extractor_gui.py'],
    pathex=[],
    binaries=[],
    datas=[('fig/logo.jpg', 'fig')],
    hiddenimports=[
        'pandas',
        'openpyxl',
        'pyautocad',
        'comtypes',
        'win32com',
        'pythoncom',
        'pywintypes',
        'openpyxl.styles',
        'openpyxl.formatting',
        'openpyxl.workbook',
        'openpyxl.worksheet',
        'tkinter',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'tkinter.ttk',
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
        're',
        'sre_compile',
        'sre_parse',
        'sre_constants',
        'logging',
        'os',
        'sys',
        'pathlib',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='PID_Extractor',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)